name: Docker Image CI Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile: [
          'Dockerfile',
          'Dockerfile_3.10',
          'Dockerfile_3.8'
        ]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file .devcontainer/${{ matrix.dockerfile }} --tag my-image-name:${{ matrix.dockerfile }}-$(date +%s)

    - name: install requirements
      run: |
        make install
    - name: run test
      run: |
        make test
    - name: run linting
      run: |
        make lint
    - name: run formatting (black)
      run: |
        make format
    - name: make pdf
      run: |
        make pdf
    - run: echo "🍏 This job's status is ${{ job.status }}."